# Generated by Django 4.2.7 on 2024-03-22 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='applicant_site',
            field=models.CharField(default='None', max_length=300),
        ),
    ]
