# Generated by Django 4.2.7 on 2024-03-25 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_alter_urls_applicant_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urls',
            name='applicant_site',
        ),
        migrations.AddField(
            model_name='urls',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
    ]
